config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('users.urls')),
    path('accounts/', include('allauth.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home_view, name='home'),
    path('training-calendar/', CalendarListView.as_view(), name='calendar'),
    path('training-calendar/<int:training_id>/', training_view, name='training'),
    path('training-calendar/<training_id>/delete/', TrainingDeleteView.as_view(), name='delete_training'),
    path('training-calendar/<training_id>/update/', TrainingUpdateView.as_view(), name='update_training'),
    path('training-calendar/create', TrainingCreateView.as_view(), name='create_training'),
    path('profile/', profile_view, name='profile'),
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('articles/<int:pk>', ArticleDetailView.as_view(), name='articles_detail'),
    path('chat/', chat_view, name='chat'),
    path('chat_get_messages/<int:chat_id>/', get_messages_view, name='chat_get_messages'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone as tz
from .managers import CustomUserManager
from django.core.validators import RegexValidator


class IntegerRangeField(models.IntegerField):
    """Кастомное поле модели для установления минимального и максимального значения числа"""

    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)

    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value': self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField('Email', unique=True)
    is_trainer = models.BooleanField(_('Тренер'), default=False)
    gym = models.ForeignKey('Gym', on_delete=models.CASCADE, verbose_name=_('Зал'), null=True, blank=True)
    image = models.ImageField(_('Аватарка'), null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def __str__(self):
        return self.get_full_name()

    class Meta:
        verbose_name = _("Пользователь")
        verbose_name_plural = _("Пользователи")


class ClientTrainer(models.Model):
    client_id = models.OneToOneField('CustomUser', on_delete=models.CASCADE, related_name='client', unique=True,
                                     null=True, blank=True, verbose_name=_('Клиент'))
    trainer_id = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='trainer', null=True,
                                   blank=True, verbose_name=_('Тренер'))

    def __str__(self):
        return self.client_id.get_full_name()

    class Meta:
        verbose_name = _('Пара клиент-тренер')
        verbose_name_plural = _('Пары клиент-тренер')


class ChatMessage(models.Model):
    chat = models.ForeignKey(ClientTrainer, on_delete=models.CASCADE, verbose_name=_("Чат"))
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name=_("Пользователь"))
    message = models.TextField(_("Сообщение"))
    pub_date = models.DateTimeField(_('Дата сообщения'), default=tz.now)

    class Meta:
        ordering = ['pub_date']
        verbose_name = _("Сообщение в чате")
        verbose_name_plural = _("Сообщения в чате")

    def __str__(self):
        return self.message


class Training(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE, related_name='trainings', unique_for_date='date',
                             verbose_name=_('Пользователь'))
    title = models.CharField(max_length=40, verbose_name=_('Заголовок'))
    content = models.TextField(null=True, blank=True, max_length=1000, verbose_name=_('Контент'))
    date = models.DateField(verbose_name='Дата')
    is_completed = models.BooleanField(verbose_name=_('Тренировка завершена'))
    is_missed = models.BooleanField(verbose_name=_('Тренировка пропущена'))
    comment = models.CharField(null=True, blank=True, max_length=500, verbose_name=_('Комментарий'))

    # client_trainer_id = models.ForeignKey('ClientTrainer', on_delete=models.CASCADE, related_name='trainer')

    def get_absolute_url(self):
        return reverse('training', kwargs={"training_id": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Тренировка")
        verbose_name_plural = _("Тренировки")
        constraints = [
            models.UniqueConstraint(fields=['user', 'date'], name='Unique')
        ]


class Gym(models.Model):
    address = models.CharField(max_length=150, verbose_name=_('Зал'))

    def __str__(self):
        return self.address

    class Meta:
        verbose_name = _("Тренажёрный зал")
        verbose_name_plural = _("Тренажёрные залы")


class UserResult(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, unique=True, verbose_name=_('Пользователь'))
    deadlift = IntegerRangeField(null=True, blank=True, min_value=0, max_value=600, verbose_name=_('Становая'))
    squats = IntegerRangeField(null=True, blank=True, min_value=0, max_value=600, verbose_name=_('Приседания'))
    benchpress = IntegerRangeField(null=True, blank=True, min_value=0, max_value=600, verbose_name=_('Жим'))

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = _("Результаты пользователя")
        verbose_name_plural = _("Результаты пользователей")


class BookingSeasonTickets(models.Model):
    phone_regex = RegexValidator(
        regex=r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$',
        message=_("Введите правильный номер телефона"))
    phone_number = models.CharField(validators=[phone_regex], max_length=17, verbose_name=_('Номер клиента'))

    def __str__(self):
        return self.phone_number

    class Meta:
        verbose_name = _("Номер для бронирования")
        verbose_name_plural = _("Номера для бронирования")


class WorkoutАrticle(models.Model):
    title = models.CharField(_('Заголовок'), max_length=40)
    preview_image = models.ImageField(_("Картинка"))
    date = models.DateField(_('Дата'))
    content = models.TextField(_('Контент'), max_length=50000)
    allowed_by_admin = models.BooleanField(_("Одобрено администратором к публикации"), default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Спортиная статья")
        verbose_name_plural = _("Спортивные статьи")

users/views.py
from datetime import timedelta, datetime
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.db.models import Q

from .forms import TrainingCreateForm, TrainingUpdateForm, UserGymForm, UserImageForm, UserChangeTrainerForm, \
    UserChangeResultsForm, BookingSeasonTicketsForm, ChatMessageForm
from .models import *


def home_view(request):
    """Логика домашней страницы с бронированием абонемента"""
    if request.method == 'POST':
        bookingform = BookingSeasonTicketsForm(request.POST)
        if bookingform.is_valid():
            bookingform.save()
    else:
        bookingform = BookingSeasonTicketsForm()
    return render(request, 'users/home.html', {'bookingform': bookingform})


class CalendarListView(ListView):
    model = Training

    '''В queryset передаю тренировочные дни, которые входят в необходимый диапазон'''

    def get_queryset(self):
        seven_days = timedelta(7)

        return Training.objects.filter(Q(user_id=self.request.user.id) &
                                       Q(date__gte=tz.localtime(tz.now()).date() - seven_days) &
                                       Q(date__lte=tz.localtime(tz.now()).date() + seven_days)).order_by('date')

    '''В контексте передаю все 15 дней, которые должны быть отражены, тренировочные дни и сегодняшний день'''
    '''Полностью осознаю, что данное решение - костыль с кучей логики в шаблоне'''

    def get_context_data(self, **kwargs):
        context = super(CalendarListView, self).get_context_data(**kwargs)
        start_date = tz.localtime(tz.now()).date() - timedelta(7)
        training_days = list(Training.objects.filter(user_id=self.request.user.id).values('date'))
        context['training_days_clean'] = [day['date'] for day in training_days]
        context['days'] = [start_date + timedelta(day) for day in range(15)]
        context['today'] = tz.localtime(tz.now()).date()
        return context


def training_view(request, training_id):
    if not request.user.is_authenticated:
        return redirect('account_login')
    training = get_object_or_404(Training,
                                 Q(user=request.user) &
                                 Q(pk=training_id))
    context = {
        'training': training,
    }
    return render(request, 'users/training_detail.html', context)


class TrainingCreateView(CreateView):
    model = Training
    form_class = TrainingCreateForm
    template_name = 'users/training_create.html'

    def form_valid(self, form):
        form.instance.user_id = self.request.user.id
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TrainingCreateView, self).get_context_data(**kwargs)
        context['date'] = datetime.strptime(self.request.GET.get('date', ''), '%Y-%m-%d').date()
        return context


class TrainingUpdateView(UpdateView):
    model = Training
    pk_url_kwarg = 'training_id'
    template_name = 'users/training_update.html'
    form_class = TrainingUpdateForm


class TrainingDeleteView(DeleteView):
    model = Training
    success_url = reverse_lazy('calendar')
    pk_url_kwarg = 'training_id'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def profile_view(request):
    if not request.user.is_authenticated:
        return redirect('account_login')
    """ Функция отображает и меняет выбранного тренера, картинку профиля, тренажёрный зал, результаты пользователя"""

    # Попытка получить связь тренера и пользователя в которой учавствует текущий пользовател
    try:
        client_trainer = ClientTrainer.objects.get(client_id=request.user.id)

    # Если такая связь не найдена она создаётся, в качестве клиента передаётся текущий пользователь
    except:
        client_trainer = ClientTrainer(client_id=request.user)
        client_trainer.save()
        client_trainer = ClientTrainer.objects.get(client_id=request.user)

    # Если пользоваетель смотрит или меняет картинку
    if request.method == 'POST' and ('image-image' in request.POST):
        imageform = UserImageForm(request.POST, request.FILES, prefix='image', instance=request.user)
        if imageform.is_valid():
            imageform.save()
    else:
        imageform = UserImageForm(prefix='image')

    # Если пользоваетель смотрит или меняет тренажёрный зал
    if request.method == 'POST' and ('gym-gym' in request.POST):
        gymform = UserGymForm(request.POST, prefix='gym', instance=request.user)
        if gymform.is_valid():
            gymform.save()
    else:
        gymform = UserGymForm(prefix='imagegym')

    # Если пользоваетель смотрит или меняет выбранного тренера
    if request.method == 'POST' and ('changetrainer-trainer_id' in request.POST):
        changetrainerform = UserChangeTrainerForm(request.POST, instance=client_trainer, prefix='changetrainer')
        if changetrainerform.is_valid():
            changetrainerform.save()
    else:
        changetrainerform = UserChangeTrainerForm(prefix='changetrainer')

    # Попытка получить результаты прользователя
    try:
        user_results_instance = UserResult.objects.get(user=request.user.id)
    # Если результаты пользователя не найдены создаётся новая таблица с результатами
    except UserResult.DoesNotExist:
        user_results_instance = UserResult(user=request.user)
        user_results_instance = user_results_instance.save()

    # Если пользоваетель смотрит или меняет свои результаты
    if request.method == 'POST' and (
            'changeresults-deadlift' in request.POST or 'changeresults-squats' in request.POST or 'changeresults-benchpress' in request.POST):
        changeresultsform = UserChangeResultsForm(request.POST, instance=user_results_instance, prefix='changeresults')
        if changeresultsform.is_valid():
            changeresultsform.save()
        else:
            return redirect('profile')
    else:
        changeresultsform = UserChangeResultsForm(prefix='changeresults')

    results = UserResult.objects.get(user=request.user)

    choices_gym = [(e.id, e.address) for e in Gym.objects.all()]

    choices_trainer = [(t.id, t.get_full_name()) for t in CustomUser.objects.filter(is_trainer=True)]

    context = {
        'gymform': gymform,
        'imageform': imageform,
        'changetrainerform': changetrainerform,
        'changeresultsform': changeresultsform,
        'choices_gym': choices_gym,
        'choices_trainer': choices_trainer,
        'client_trainer': client_trainer,
        'results': results,
    }

    return render(request, 'users/profile.html', context)


class ArticleListView(ListView):
    model = WorkoutАrticle
    template_name = 'users/article_list.html'

    def get_queryset(self):
        return WorkoutАrticle.objects.all().order_by('-date')


class ArticleDetailView(DetailView):
    model = WorkoutАrticle
    pk_url_kwarg = 'pk'
    template_name = 'users/article_detail.html'


def chat_view(request):
    if not request.user.is_authenticated:
        return redirect('account_login')
    # Если пользователь - тренер
    if request.user.is_trainer:
        chats = ClientTrainer.objects.filter(trainer_id=request.user)

        chat_id = request.GET.get('chat', '')
        if chat_id:
            try:
                messages = ChatMessage.objects.filter(chat_id=request.GET.get('chat', '')).order_by('-pub_date')
            except messages.DoesNotExist:
                messages = None
            current_chat = ClientTrainer.objects.get(id=request.GET.get('chat', ''))
        else:
            messages = None
            current_chat = None

        context = {
            'messages': messages,
            'chats': chats,
            'current_chat': current_chat
        }
    # Если пользователь - клиент
    else:
        try:
            chat = ClientTrainer.objects.get(client_id=request.user)
        except:
            return redirect('profile')
        try:
            messages = ChatMessage.objects.filter(chat__client_id=request.user.id).order_by('-pub_date')
        except:
            messages = None

        context = {
            'chat': chat,
            'messages': messages,
        }

    # Форма
    if request.method == 'POST':
        form = ChatMessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            if request.user.is_trainer:
                if not request.GET.get('chat', ''):
                    return redirect('chat')
                message.chat_id = request.GET.get('chat', '')
            else:
                message.chat_id = ClientTrainer.objects.get(client_id=request.user.id).id
            message.author = request.user
            message.save()
            context.update({'form': message})
    else:
        form = ChatMessageForm()
        context.update({'form': form})

    return render(request, 'users/chat.html', context)


def get_messages_view(request, chat_id):
    """ Получаю все сообщения в чате где есть текущий пользователь
    [
       {
          "model":"users.chatmessage",
          "pk":1,
          "fields":{
             "chat":44,
             "author":1,
             "message":"Привет",
             "pub_date":"2021-06-13T16:03:28Z",
          }
       }
    ]
    """
    if request.user.is_trainer:
        messages = ChatMessage.objects.filter(chat_id=chat_id).order_by('-pub_date')
    else:
        messages = ChatMessage.objects.filter(chat__client_id=request.user.id).order_by('-pub_date')

    messages_json = serializers.serialize('json', messages)
    return HttpResponse(messages_json, content_type='application/json')

users/templates/users/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}
    <section class="news">
        <div class="container">
            <div class="col-8 mt-5 mb-5">
                <img src="{{ object.preview_image.url }}" class="innews_img col-12" alt="" height="400">
                <div class="innews_description mt-2">
					<span class="innews_h white">
						{{ object.title }}
					</span><br>
                    <span class="news_date">
                        {{ object.date }}
					</span>
                    <div class="innews_text white">
                        {{ object.content|linebreaks }}
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

users/templates/users/article_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Статьи о спорте' %}
{% endblock %}

{% block content %}
    <section class="news">
        <h2 class="page_h white mt-5">{% trans 'Полезная информация о тренировках' %}</h2>
        <div class="container">
            <div class="row d-flex">
                {% for article in object_list %}
                    {% if article.allowed_by_admin %}
                        <div class="col-4">
                            <a href="{% url 'articles_detail' article.pk %}" class="news_item ">
                                <img src="{{ article.preview_image.url }}" alt="" class="news_img" width="350"
                                     height="350">
                                <div class="news_description">
							<span class="news_h white">
								{{ article.title }}
							</span>
                                    <span class="news_date white mt-2">
								{{ article.date }}
							</span>
                                </div>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/training_create.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Создание тренировки' %}
{% endblock %}

{% block content %}
    <div class="calendar-background">
        <div class="training-line-empty training-line">
            <div class="container">
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col-5 mt-2">
                        <h2 class="training-detail-dayweek training-detail-line-save-update">{% trans 'Дата тренировки' %}</h2>
                        <input class="training-create-form-field-date"
                               form="create-form"
                               type="text"
                               name="date"
                               value="{{ date|date:'j.m.Y' }}"
                               required="" id="id_date">
                    </div>
                    <div class="col-4 d-flex justify-content-around align-items-center">
                        <button form="create-form" type="submit"
                                class="training-detail-edit-delete training-detail-line-save-update"><img
                                src="{% static 'img/edit-black.svg' %}"

                                class="mr-2" alt="" height="17px"
                                width="17px">{% trans 'Сохранить' %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert-training" role="alert">
                        {{ error|escape }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert-training" role="alert">
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-2"></div>
                <div class="col-5">
                    <form action="{% url 'create_training' %}?date={{ request.GET.date }}" method="post"
                          id="create-form">
                        {% csrf_token %}
                        <div class="d-flex flex-column">
                            <input class="training-create-form-field  mt-4" placeholder="{% trans 'Заголовок тренировки' %}"
                                   type="text"
                                   name="title"
                                   value="{{ form.title.value|default:'' }}"
                                   maxlength="40"
                                   required="" id="id_title">
                            <textarea class="training-create-form-field  mt-4" placeholder="{% trans 'Описание тренировки' %}"
                                      name="content" rows="10"
                                      id="id_content">{{ form.content.value|default:'' }}</textarea>
                            <div class="mt-4 row d-flex justify-content-between">
                                <div class="ml-3 row">
                                    <input class="mt-2 mr-1" type="checkbox" name="is_missed"
                                           id="id_is_missed">
                                    <p class="training-detail-label-checkbox">{% trans 'Тренировка пропущена' %}</p>
                                </div>
                                <div class="mr-3 row">
                                    <input class="mt-2 mr-1" type="checkbox" name="is_completed"
                                           id="id_is_completed">
                                    <p class="training-detail-label-checkbox">{% trans 'Тренировка завершена' %}</p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="training-detail-comment-line training-detail-comment-line-empty"></div>
        <div class="container">
            <div class="row">
                <div class="col-2"></div>
                <div class="col-5 d-flex flex-column">
                    <p class="training-detail-comment-title mb-2">{% trans 'Комментарий' %}</p>
                    <input class="training-create-form-field " type="text" name="comment" maxlength="200"
                           id="id_comment" form="create-form" value="{{ form.comment.value|default:'' }}">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/training_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block title %}
    {% trans 'Изменение тренировки' %}
{% endblock %}

{% block content %}
    <div class="calendar-background">
        <div class="training-line-empty training-line">
            <div class="container">
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col-5 mt-2">
                        <h2 class="training-detail-dayweek training-detail-line-save-update">{% trans 'Дата тренировки' %}</h2>
                        <input class="training-create-form-field-date"
                               form="create-form"
                               type="text"
                               name="date"
                               value="{{ form.date.value|date:'j.m.Y' }}"
                               required="" id="id_date">
                    </div>
                    <div class="col-4 d-flex justify-content-around align-items-center">
                        <button form="create-form" type="submit"
                                class="training-detail-edit-delete training-detail-line-save-update"><img
                                src="{% static 'img/edit-black.svg' %}"

                                class="mr-2" alt="" height="17px"
                                width="17px">{% trans 'Сохранить' %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert-training" role="alert">
                        {{ error|escape }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert-training" role="alert">
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-2"></div>
                <div class="col-5">
                    <form action="{% url 'update_training' training.id %}" method="post"
                          id="create-form">
                        {% csrf_token %}
                        <div class="d-flex flex-column">
                            <input class="training-create-form-field  mt-4" placeholder="{% trans 'Заголовок тренировки' %}"
                                   type="text"
                                   name="title"
                                   value="{{ form.title.value|default:'' }}"
                                   maxlength="40"
                                   required="" id="id_title">
                            <textarea class="training-create-form-field  mt-4" placeholder="{% trans 'Описание тренировки' %}"
                                      name="content" rows="10"
                                      id="id_content">{{ form.content.value|default:'' }}</textarea>
                            <div class="mt-4 row d-flex justify-content-between">
                                <div class="ml-3 row">
                                    <input class="mt-2 mr-1" type="checkbox" name="is_missed"
                                           id="id_is_missed"
                                            {% if form.is_missed.value %}
                                           checked
                                            {% endif %}>
                                    <p class="training-detail-label-checkbox">{% trans 'Тренировка пропущена' %}</p>
                                </div>
                                <div class="mr-3 row">
                                    <input class="mt-2 mr-1" type="checkbox" name="is_completed"
                                           id="id_is_completed"
                                            {% if form.is_completed.value %}
                                           checked
                                            {% endif %}>
                                    <p class="training-detail-label-checkbox">{% trans 'Тренировка завершена' %}</p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="training-detail-comment-line training-detail-comment-line-empty"></div>
        <div class="container">
            <div class="row">
                <div class="col-2"></div>
                <div class="col-5 d-flex flex-column">
                    <p class="training-detail-comment-title mb-2">{% trans 'Комментарий' %}</p>
                    <input class="training-create-form-field " type="text" name="comment" maxlength="200"
                           id="id_comment" form="create-form" value="{{ form.comment.value|default:'' }}">
                </div>
            </div>
        </div>
    </div>
{% endblock %}